FROM node:13.5.0-alpine3.10 as build-step
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.17.0-alpine as prod-stage
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-step /app/dist/mean-stack-customer-app/ /usr/share/nginx/html
EXPOSE 8090
CMD ["nginx", "-g", "daemon off;"]
